version: "2"
services:
  mesos_slave:
    build: "./mesos"
    command: |
        mesos slave \
            --advertise_ip=192.168.99.102 \
            --log_dir=/var/log/mesos \
            --containerizers=docker,mesos \
            --executor_registration_timeout=5mins \
            --work_dir=/var/mesos/work \
            --docker=/usr/bin/docker \
            --docker_mesos_image=mesosdocker_mesos_slave \
            --docker_socket=/var/run/docker.sock \
            --master=zk://192.168.99.100:2181/mesos \
            --resources='ports:[80-80,443-443,9090-9091,10000-10100,31000-32000]' \
            --no-systemd_enable_support
    privileged: true
    pid: host
    environment:
      MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
      MESOS_CONTAINERIZERS: "docker,mesos"
    network_mode: host
    ports:
      - "5051:5051"  # Mesos-slave
    volumes:
      - "/sys:/sys"
      - "/var/lib/docker/aufs:/var/lib/docker/aufs"
      - "/usr/local/lib/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/usr/local/bin/docker:/usr/local/bin/docker"
  mesos_dns:
    image: "mesosphere/mesos-dns:0.5.2"
    command: "/usr/bin/mesos-dns -v=2 -config=/config.json"
    network_mode: host
    volumes:
      - "./mesos-dns/config.json:/config.json"
      - "/tmp"
